import '../models/user_model.dart';
import '../enums/user_role.dart';

// REPLACE WITH API DATA SOURCE
final List<UserModel> mockUsers = <UserModel>[
  const UserModel(
    id: 'u1',
    fullName: 'Amina Njeri',
    username: '@aminan',
    age: 22,
    role: UserRole.student,
    courses: <String>['Computer Science', 'UI Systems', 'Product Design'],
    bio: 'Designing calm interfaces and building study circles around campus.',
    isOnline: true,
    location: 'Nairobi, Kenya',
    avatarSeed: 'AN',
    year: 'Year 4',
  ),
  const UserModel(
    id: 'u2',
    fullName: 'Brian Otieno',
    username: '@briano',
    age: 27,
    role: UserRole.alumni,
    courses: <String>['Software Engineering', 'Cloud Architecture'],
    bio: 'Works in platform engineering and mentors first-year builders.',
    isOnline: true,
    location: 'Mombasa, Kenya',
    avatarSeed: 'BO',
    year: 'Alumni',
  ),
  const UserModel(
    id: 'u3',
    fullName: 'Lydia Wanjiku',
    username: '@lydiaw',
    age: 21,
    role: UserRole.student,
    courses: <String>['Data Science', 'Statistics', 'ML Foundations'],
    bio: 'Exploring data products, dashboards, and campus research groups.',
    isOnline: false,
    location: 'Kisumu, Kenya',
    avatarSeed: 'LW',
    year: 'Year 3',
  ),
  const UserModel(
    id: 'u4',
    fullName: 'Kevin Muriuki',
    username: '@kevinm',
    age: 29,
    role: UserRole.alumni,
    courses: <String>['Cybersecurity', 'Network Systems'],
    bio:
        'Helping students land internships and build portfolio-ready projects.',
    isOnline: false,
    location: 'Nakuru, Kenya',
    avatarSeed: 'KM',
    year: 'Alumni',
  ),
  const UserModel(
    id: 'u5',
    fullName: 'Zuri Hassan',
    username: '@zurih',
    age: 23,
    role: UserRole.student,
    courses: <String>['Interaction Design', 'Animation', 'Frontend'],
    bio: 'Makes expressive mobile UI systems and short motion studies.',
    isOnline: true,
    location: 'Eldoret, Kenya',
    avatarSeed: 'ZH',
    year: 'Year 5',
  ),
  const UserModel(
    id: 'u6',
    fullName: 'Faith Adhiambo',
    username: '@faitha',
    age: 26,
    role: UserRole.alumni,
    courses: <String>['Business Analytics', 'Leadership'],
    bio: 'Runs mentorship sessions and career prep for final-year students.',
    isOnline: true,
    location: 'Nairobi, Kenya',
    avatarSeed: 'FA',
    year: 'Alumni',
  ),
];
